#!name=WPS会员
#!desc=WPS解锁本地会员,支持大陆版以及非大陆版(2022.07.10)
#!openUrl=https://github.com/I-am-R-E/Functional-Store-Hub/tree/Master/WPSOffice
#!author=@R·E https://t.me/Functional_Store_Hub

[Script]
WPS会员 = type=http-response,pattern=^https?:\/\/.account\.wps\.(com|cn)(:\d+)?\/api\/users\/\w+\/overview$,script-path=https://raw.githubusercontent.com/ytxujing/Jasper/refs/heads/master/Shadowrocket/Script/WPS.js,requires-body=1,timeout=10

[MITM]
hostname = %APPEND% account.wps.cn, account.wps.com
